### ISSUE TITLE
window.opener corruption after pressing "Install..."

### ISSUE THREAD

**Issue by supahgreg** [skrul/greasefire#20]
Sometimes the script install dialog appears, but most of the time it does not.  When it does not, one of the following occurs:
1. Opening window chrome is messed up, only showing the "502 bad gateway" error page.  [screenshot](http://phob.net/greasefire_502badGateway_in_windowOpener.png)
2. Opening window chrome is messed up, showing the "502 bad gateway" error page, **but** with the user script source somehow overlayed.  [screenshot](http://phob.net/greasefire_script_install_source_in_windowOpener.png)

Using HEAD.  Build identifier: Mozilla/5.0 (Windows NT 6.1; rv:6.0a1) Gecko/20110510 Firefox/6.0a1

**Comment by erikvold** [comment]
I've noticed quite a few gateway and other errors, they seemed to be coming from USO but I haven't looked into that.

**Comment by supahgreg** [comment]
Believe I found the cause... supahgreg/greasefire@fe71c4bd4e2902da0305e435ddd51e7f1b4b8aaf

**Comment by erikvold** [comment]
#22 should have resolved this.
