### ISSUE TITLE
Handle script install if window.opener is closed

### ISSUE THREAD

**Issue by supahgreg** [skrul/greasefire#22]
Looks like a script simply won't install if the `window.opener` no longer exists.  Needs to be a fallback/replacement... maybe opening the USO page?

**Comment by erikvold** [comment]
I don't think we need to use `window.opener`, for GM we can just use the most recent window, for Scriptish we can use the JSM we have for installing scripts.

**Comment by supahgreg** [comment]
Did some quick testing.  Even with the Scriptish change, the following problems exist:
- Unable to install if Greasefire is the only window open and you try to install
- Unable to install if Greasefire is the only window open, you open a new window, and then try to install

**Comment by erikvold** [comment]
> Unable to install if Greasefire is the only window open and you try to install

This is more the fault of Scriptish and GM, we should remove the dep on a `window` in there.

> Unable to install if Greasefire is the only window open, you open a new window, and then try to install 

This should be resolved by using the most recent window.

**Comment by supahgreg** [comment]
How does this look?  [/supahgreg/greasefire/compare/issue-22](https://github.com/supahgreg/greasefire/compare/issue-22)

Got rid of `window.opener` in favor of finding a recent window, or creating a new one if none were found.

The problem I mentioned in my last post was that `installSelected` was trying to reference `window.opener`, which had been closed.

**Comment by erikvold** [comment]
@supahgreg why'd you move your `issue-22` branch?

**Comment by supahgreg** [comment]
Busy screwing it up with rebase :)  Will get it back shortly...

**Comment by supahgreg** [comment]
There we go (supahgreg/greasefire@ba89f0425b54f932580aac94e355eaaa894ec6bc).
