### ISSUE TITLE
Inactive icon for "picker" browser throbber

### ISSUE THREAD

**Issue by supahgreg** [skrul/greasefire#33]
I'd suggest showing `chrome://global/skin/icons/notloading_16.png` when content isn't loading.

**Comment by supahgreg** [comment]
supahgreg/greasefire@e01f92a84b8a195c007b1954940a28be2a526f06

**Comment by erikvold** [comment]
> I'd suggest showing chrome://global/skin/icons/notloading_16.png when content isn't loading.

Why does this feel right to you?

Removing the throbber seems like common practice, and it's easy to spot a missing throbber icon. Trying to determine if the throbber has stopped or is still moving is more difficult.

**Comment by supahgreg** [comment]
Primarily because with nothing there it is just an empty, unused notch of space.  That looks unattractive, to me.

Maybe the link to open the USO page in a new tab (#25) could fill that spot.

**Comment by erikvold** [comment]
I'm going to close this since I want to rewrite the page as a addon page with the addon kit now.
