### ISSUE TITLE
Update the "bad includes" list

### ISSUE THREAD

**Issue by supahgreg** [skrul/greasefire#37]
Need to update [the list](https://github.com/skrul/greasefire/blob/master/java/greasefire-scraper/src/com/skrul/greasefire/Generate.java#L49).  Some ones I've noticed:
- `*://*/*`
- `http*://*.*`
- `*.*.*/*`

These I'm not certain about:
- `*://*/ads.php`
- `*://*.google.*/*`
- `http://*.net/game.php*`
- `http://*.net`

**Comment by skrul** [comment]
I would love to have a way to automate this rather than playing whack-a-mole.  When building the index, I could imagine getting a few thousand popular URLs, running all the @includes against them, and if a pattern matches too many URLs just not include it.

Thoughts?
