### ISSUE TITLE
Error in error console when the Scriptish toolbarbutton is not used

### ISSUE THREAD

**Issue by erikvold** [skrul/greasefire#4]
Error: document.getElementById("scriptish-button") is null
Source File: chrome://greasefire/content/browser.js
Line: 54

**Comment by tony1223** [comment]
It should be a easy one , 
but I am not sure how could i reproduce it for "scriptish toolbarbutton is not used ".

I try to restore default but nothing happened, i guess am doing somethin wrong.

any ideas?

**Comment by erikvold** [comment]
you should be able to use the [Toolbar customization](http://kb.mozillazine.org/Toolbar_customization_-_Firefox) to remove the toolbar button, then you'd need to open a new window or restart.

**Comment by tony1223** [comment]
I test and found this is covered by Issue 8.
