### ISSUE TITLE
Launch v1.0.6

### ISSUE THREAD

**Issue by erikvold** [skrul/greasefire#42]
Making a issue to keep open for the v1.0.6 milestone b/c I can't add new issues to a milestone w/out open issues...

**Comment by erikvold** [comment]
For tracking: https://github.com/skrul/greasefire/issues?milestone=1&state=open

**Comment by erikvold** [comment]
@skrul v1.0.6 is ready to go imo.

**Comment by skrul** [comment]
Just submitted it to AMO.
