### ISSUE TITLE
Greasefire won't install in Firefox 4

### ISSUE THREAD

**Issue by havanamike** [skrul/greasefire#46]
Everything I tried to install the latest Greasefire will not work. I have GreaseMonkey version 0.9.3 and trying to install 1.0.6

**Comment by erikvold** [comment]
What happens when you try to install Greasefire?

**Comment by havanamike** [comment]
It shows in the extensions list,but as disabled. When I try to click the Enable button it does not respond. If I then restart Firefox, it is no longer displayed in the listing; like it never really installed.

**Comment by havanamike** [comment]
I have attempted to install from the FireFox Add-ons page and downloaded the xpi locally and tried to install from my desktop. Neither manner is working.

**Comment by supahgreg** [comment]
Any errors in the error console?

**Comment by erikvold** [comment]
@havanamike what OS are you on?

**Comment by havanamike** [comment]
Windows Vista
FF4
GreaseMonkey version 0.9.3

**Comment by havanamike** [comment]
They really need to move that Close button

**Comment by havanamike** [comment]
Well, I guess we can close this. When I started up FF this evening, I noticed the Greasemonkey icon had the fire behind it again. Looks like GF finally installed.
