### ISSUE TITLE
Greasefire prevent Nightly to startup

### ISSUE THREAD

**Issue by tbs** [skrul/greasefire#53]
After today update of nightly build, my browser never startup until I disabled the extension.

Mozilla/5.0 (Windows NT 6.1; WOW64; rv:8.0a1) Gecko/20110810 Firefox/8.0a1

Someone else confirms this problem?

**Comment by supahgreg** [comment]
Confirmed.

Build identifier: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:8.0a1) Gecko/20110810 Firefox/8.0a1

**Comment by supahgreg** [comment]
`resource://gre/modules/ISO8601DateUtils.jsm` has been removed

https://bugzilla.mozilla.org/show_bug.cgi?id=543535

**Comment by erikvold** [comment]
Closed by 0d8340b739edfd532a85c95609b4085c4623e9dc
