### ISSUE TITLE
no longer updates

### ISSUE THREAD

**Issue by lastmoexit** [skrul/greasefire#55]
using Firefox 3.6.22, Greasefire index will no longer update ...stuck on 60742 ...when update button is clicked, immediately says Update Complete

**Comment by erikvold** [comment]
hmm looks like the `include.dat` and `exclude.dat` files are missing in http://skrul.com/projects/greasefire/update.php

**Comment by erikvold** [comment]
I'm not sure what is going on there, maybe @skrul can take a look at some point?

**Comment by skrul** [comment]
Hm, yes there does seem to be a problem with the program that builds the databases:

INFO: page: 7 25 scripts
Sep 7, 2011 2:08:40 AM com.skrul.greasefire.Generate main
INFO: Scripts dir: scripts
Sep 7, 2011 2:08:40 AM com.skrul.greasefire.Generate main
INFO: Dest dir: tmp
Sep 7, 2011 2:09:06 AM com.skrul.greasefire.Generate main
INFO: at 0 of 67274, last id was 100000
Sep 7, 2011 2:09:31 AM com.skrul.greasefire.Generate main
INFO: at 1000 of 67274, last id was 101152
Exception in thread "main" java.lang.NumberFormatException: null
        at java.lang.Integer.parseInt(Integer.java:417)
        at java.lang.Integer.parseInt(Integer.java:499)
        at com.skrul.greasefire.Generate.main(Generate.java:123)
include.dat : no such file or directory
exclude.dat : no such file or directory
adding: scripts.db(in = 2048) (out= 160)(deflated 92%)
adding: info.ini(in = 36) (out= 36)(deflated 0%)
cp: include.dat: No such file or directory
cp: exclude.dat: No such file or directory
cp: scripts.txt: No such file or directory

I'll have to take a closer look in a little bit, but this is interesting, it has been running for a very log time without a problem :)

**Comment by lastmoexit** [comment]
thank you :)

**Comment by Mostafa20xx** [comment]
for me too no update since August 28 
any solution?

**Comment by lastmoexit** [comment]
just curious if there are any updates on this issue ...thanks

**Comment by erikvold** [comment]
might be a little while.

**Comment by Mostafa20xx** [comment]
when this is too much?!

**Comment by lastmoexit** [comment]
hello, again ...just dropping a note wondering how things are coming along ...thanks

**Comment by limex** [comment]
I'm also desperately waiting for a fix. I would be very sad if this great tool would be discontinued.

**Comment by frog23** [comment]
For those who don't mind replacing the files in your Firefox installation, you can get an updated index [here](http://dl.dropbox.com/u/1844215/index_2011-11-05T09%3A17%3A00Z.jar)
just extract the files in the archive and put them in the `greasefire@skrul.com/indexes` folder of your Firefox installation.
BTW: This index has a lot more blacklisted scripts, because it used the Regular Expression that I described [here](44#issuecomment-2415175). 
This is only a manual fix. @skrul: could you please take care of this.

**Comment by lastmoexit** [comment]
@frog23: thank you for the manual fix ...is there a link i can regularly check for updates containing the latest .jar file until the issue is resolved?

**Comment by frog23** [comment]
@lastmoexit: sorry no, as I have currently no time for this. I might update the provided file manually every couple of weeks, if the problem doesn't get fixed soon. If somebody wants to set up an new system that automatically creates these files, I'd be glad to provide my modified version of the software.

**Comment by skrul** [comment]
Hey all, I think I got this fixed last night.  Let me know if it is working again!

**Comment by frog23** [comment]
@skrul I just tested it and it looks great. Thanks for fixing it. This issue can be closed now.

**Comment by skrul** [comment]
Thanks for testing it out :)
