### ISSUE TITLE
Filter in Firefox does not work for capitalized letters

### ISSUE THREAD

**Issue by frog23** [skrul/greasefire#61]
(copied from http://code.google.com/p/greasefire/issues/detail?id=17 plus some minor adjustments)

In the Firefox version, the filtering of the scripts does not work correctly. When typing any capitalized letter, no results are returned. This is because in the filter, the filter string is matched against a lower case version of the name of the script, but the search term itself is not converted to lower case. In order to fix this, line 266 in https://github.com/skrul/greasefire/blob/master/firefox/chrome/content/picker.js#L266 should be changed from 

`if (e.name.toLowerCase().indexOf(filter[i]) < 0) {`

to 

`if (e.name.toLowerCase().indexOf(filter[i].toLowerCase()) < 0) {`

I have neither tested nor checked, if this bug also exists in the chrome version of Greasefire.
It is not a big issue, once you know that you are only supposed to type lower case filter words, but it is still confusing for people who are unaware of this bug.

**Comment by erikvold** [comment]
Closed by ddd54158a9089d161b0baa9db39172b9e7e445ce
