### ISSUE TITLE
make updateURL adjustable

### ISSUE THREAD

**Issue by frog23** [skrul/greasefire#63]
It would be nice to have the [updateURL](https://github.com/skrul/greasefire/blob/master/firefox/components/gfUpdaterService.js#L14) of greasefire be adjustable, so I can point them to my own index-files. This would now be especially useful as #44 and #55 are not resolved.
The updateURL could be changed via the settings panel of the addon, or via a suitable setting in about:config.

**Comment by erikvold** [comment]
Closed by 0bcf16b626b96c9fcab3904b1f4afbb3fda74326
