### ISSUE TITLE
Index update: error updating

### ISSUE THREAD

**Issue by Jan02** [skrul/greasefire#74]
Timestamp: 2013-08-29 07:43:04
Error: [Exception... "Not enough arguments [nsIWebBrowserPersist.saveURI]"  nsresult: "0x80570001 (NS_ERROR_XPC_NOT_ENOUGH_ARGS)"  location: "JS frame :: jar:file:///Z:/portableapps/PortableApps/FirefoxPortable/Data/profile/extensions/greasefire@skrul.com.xpi!/components/gfUpdaterService.js :: gfUpdaterService_startUpdate/< :: line 240"  data: no]
Source File: jar:file:///Z:/portableapps/PortableApps/FirefoxPortable/Data/profile/extensions/greasefire@skrul.com.xpi!/components/gfUpdaterService.js
Line: 245

```
    Name
    Firefox

    Version
    23.0.1

    User Agent
    Mozilla/5.0 (Windows NT 5.1; rv:23.0) Gecko/20100101 Firefox/23.0
```

**Comment by frog23** [comment]
What version of Greasefire are you using and what is your `greasefire.update_url` in `about:config`? You need to use the most recent version which was bundled by Marti: http://userscripts.org/topics/115646#posts-477889 and not the one from addons.mozilla.org.
I hope this helps
  Frog23
