### ISSUE TITLE
Error in error console when GM and Scriptish are not installed

### ISSUE THREAD

**Issue by erikvold** [skrul/greasefire#8]
Error: popup is null
Source File: chrome://greasefire/content/browser.js
Line: 57

**Comment by tony1223** [comment]
That seems we need to handle the _setupMenu/_updateMenu in browser.js to determine the popup (or a create init flag instead of detecting popup is null.)

**Comment by tony1223** [comment]
Am going to handle this easy one first

**Comment by tony1223** [comment]
fixed since 2011/5/11

**Comment by erikvold** [comment]
Hmm there seems to be a issue with your patch @tony1223, all I ever see is "Grease File.." where I should see a "# scripts available" and I never see the fire image behind the Scriptish icon.

I've saved the patch in two branches:
https://github.com/erikvold/greasefire/tree/issue-8
https://github.com/erikvold/greasefire/tree/issue-8-merge

I'm going to back it out for now.

**Comment by tony1223** [comment]
hmm , that's my bad to forget testing the feature.  This time it should work fine.

**Comment by erikvold** [comment]
yah I just tried it w/ Scriptish and that was working well.
